// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Users struct {
	ID        int64     `json:"id"`
	FirstName string    `json:"first_name"`
	LastName  string    `json:"last_name"`
	UserName  string    `json:"user_name"`
	Email     string    `json:"email"`
	Password  string    `json:"password"`
	PhoneNo   string    `json:"phone_no"`
	CreatedAt time.Time `json:"created_at"`
}
